remote_theme: atomsrivet/plainwhite-jekyll
plugins:
- jekyll-remote-theme 

title: Tsvetomira Dumbalska
author: Tsvetomira Dumbalska
email: tsvetomira.dumbalska@psy.ox.ac.uk
description: Postdoctoral Research Fellow
Department of Experimental Psychology
Wadham College
University of Oxford > # this means to ignore newlines until "show_exerpts:"
show_excerpts: true # set to true to show excerpts on the homepage


plainwhite:
  name: Tsvetomira Dumbalska
  tagline: >
   Cognitive Scientist 
   <center>
   <a href="https://www.psy.ox.ac.uk/people/tsvetomira-dumbalska">Department of Experimental Psychology</a><br>
   <a href="https://www.wadham.ox.ac.uk/people/tsvetomira-dumbalska">Wadham College</a><br>
   University of Oxford</center>
  date_format: "%b %-d, %Y"
  sitemap: true
  dark_mode: true
  social_links:
    email: tsvetomira.dumbalska@psy.ox.ac.uk
    osf: cnjr5
    orcid: 0000-0002-5761-8536
    github:  atomsrivet

  portfolio_image:  "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)

  